/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContactSection: typeof import('./src/components/ContactSection.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    NotesPreview: typeof import('./src/components/NotesPreview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionHeading: typeof import('./src/components/SectionHeading.vue')['default']
    SelectedSystems: typeof import('./src/components/SelectedSystems.vue')['default']
    WorkPrinciples: typeof import('./src/components/WorkPrinciples.vue')['default']
  }
}
